// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'metadata': string;
  'userBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
