// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beuBtn': string;
  'home': string;
  'sbButn': string;
  'sbButndis': string;
}
export const cssExports: CssExports;
export default cssExports;
